version: "3.9"

services:
  frontend:
    image: gasomar/worktoday:v1.3
    container_name: worktoday_frontend
    ports:
      - "5173:80"
    restart: unless-stopped

    depends_on:
      - app
  app:
    image: alivkas/work-today-project:1.23
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    depends_on:
      - db

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"