version: "3.8"

services:
  app:
    image: alivkas/work-today-project:1.18
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      DROPBOX_KEY: sl.u.AFcjsBzgSLtxDVrIK28fHl9s-TXj7nkmm2g3KPpMGmAmCL2eQSiL5WixZDZjDQaCsCXnEIsl7rEjMlqmOwGzPpsjhBGed7lhXe_4HZP7_UVuEAMdJG3EbtIBqnDZIJgRy4xFp-dEMhiUP8BZDsYYHSuJbqQQNJ8RrzClQbc0SSZ41OsaA5iSzL-QzBvU9kmsKUeADgFFgMLCbfwjPk2JlK4q9g7QtWVXQ7jnX38lO4j09jNJPG36zTTINsNZwLUnMfLT3SEzeghaFONtLlqVBmzdtNhzwXREBbbbrr7WzfusYz-RF46ZoqrO4m3s82KbEHkmWgYmHPKCgMJKg56BMWG0TOMfvc1yIF41Sv73XSGu4p2XfZndKcvxeDJAAvZ2ccfonD90iHCIGJMZwehcVVgiTDB3jFXol6YeQp3sq23LklJxQ4Tnt9qjkiK0nonuPjybLJ52ST_jOqknwA-VDKOWVRa_ph0ynZMLzROq0rfGN-nDlnyasDB7RKpfcklZTtAuD0AuJbV8F8FE_hifH-ylVcGysOTb0z1Zr4ts9vBTTKckS6PEez4HbDnzBO9h3r8fj2OAzca7RrNWECxGBVN4oet1sVC1EUOVHjUwV2XxByMJWX0SvYngRZpFfrljdbNuXbtVdbAAbZn5YQqwxIdi-cN0NNSyTFFesngvV_SqhZJYj6SiTAzhiya92MtY0IelV2UsGbJv1ay1uB1SWST1_EHQGvz7nV3TNHDsfD0TdqPhDpy98-4jf3B7FssbMG1edHClxYc88dMEkavmgzp34b40ee0Vi6pbpHxVglIbQn6Edixb5Ghc9Av_nP6J_xJaio0u5TMggnHy_L2w7-bl1xF5dN4EU8w6hNsFru2IH-pdDgZYduxSEFcEqKRFoQOLs-L9wvY6pqIIzphlRt3VTghDhsbovG5BQvnt7CiZ3-LXXFrY_XARScYg8_hpqIjMWGQN6w4IooVZpGBDcuNKL5s6WYgpcwFMS_fW-K8ocppQI8AoFIuuasB9HnRcc6Nw7pmSI_cuqwt-iMnKkB-iMtajoA-9Org0GcIIJfUOR-exejF3UPYQNspDBj1Jn304N3AnibzJ_Y-ChlQQk6_rR8WE8A9OgcACLZC3wIcbbMe_X6JiSWELQtQyr7ds87_7GHoUa4Rb8JnE7c_MQBw8bBu39iQ7l-lTmP-JRYavDDKNHccdWZL2L23FI_lQQ1OMmiAMvxtXN8kMnFIhL0lxSP2JQe6m2HlrB50Zh63dlmo8y1xbeUb2TwQGEr1o7jaSYdP8WwvbRBRwvsbTf1ujwaEmoNXbJB8vfKVQt4OgoR6xeK8qABQSTkZiE6WgySIeNIFM4LhR0VjrsntbvZvxN7yX3AYrTr8ucaXThkQOtwhCaQlXqbTt5tFduJEfF1RVv-QJQWWNJmNmWDMEYqHrgBX1VTQWcjNNITi09wtqsQ
    depends_on:
      - db

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
