version: "3.8"

services:
  app:
    image: alivkas/work-today-project:1.14
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      DROPBOX_KEY: sl.u.AFdLma2ieHimw0gacHMjL5yCjgk0So0SVVt7ZVVxtBvEu8d1abk2GQgGVVkyMl_wNfyEJ57VewmW6QwY4zj8DL_vlhgf5o-QLT2TOVKqWOsFYosuao325r_oenqQsxu54RUq_lpkn9q9EVWXuTNg3WXZbxVngKGH-OSnPMBts4je279HeXYfR-03yNkUaIqDK221OxT9uwYXVbw6vdLuc7HdnuZyLzLpgDjYqjfpSzc0863-rD-KK2cSPcVCs5_tm6yamo1ipTlJjSaEKoKv-naKR4-WUZh0wJIMcLY9GyhAyjJuFsh8SuXclzVWYr_ueT69fjyQ99doR7Xe6da3csOkz9u3JORInhH1IbcBaeHWpfo7-J-NfvHniN-0fmLbvImQP2QQBDD04Kmwmcpwcxf508FQW-CpaS9ACC9bw7hylYM7JkU1IbR_TgKzeOxCrYMKTEoYY534nc5Fp46UpBNTYdFcsCRGvwxpwrkbackk4Dq24xmykQZhNP9v5zx09T4nAGxY-CR-FF-CRBMJeJeYdlff0AtoIpF2pZp0HE08Dcyp47DGcrbF6bZP7MOvHuXRH7qUubsAZ-68_bTC7wavsghR6UfrIomdJlJ7W4-GF4sbOJAhto3gmK0Hox6gcNn_j32Qh2oBRWzZ9lLAigtH14OKT__PCefLYXS0D165dNi1eX4W_ScW29_GJlxC2Iq6FJTSWGeFuTj7DMNZ3YJfajZwa25SqfPO7lzygVvnIm2fgIOrG4LUprvutjnTQY28CYtyKC2k_GYZHSgS8a82lv2pTT0ybDPDf7Lp7BG5mxwKoWJQCArKREn3Mq4G3Pv74PCSf6zC9X8l-meaYFzm-tubX_2XiDJ9tElnjtcAtEx2z0F0f4HNOWNOOtkxz8mcLu0sFUWT0s6n55wVTl1ZYKQY9ZPLmjFMZkjdw4oTiAAdNiJ4P4391NkK88dXR8JsIohCK2f1qL67cx_dTHOQVP9cVxJm-VmF4VrAzLrBAGx7eHmvD8HH2_b6HQ-OF42r8v8fnsXDLxE9EiOQWKY6yz-bP_Rl9V-KL2VsJoo-Oo5o6oUDZTxAjmsUm1tw0NO_ndXBQV738vG96aw9AjBWbi_TN3tOBel6VWfhkF-8nanVUEXaY093ppW1ipLngHTSY-AS0-pUrMokRLrbELGjPq0KMrfn9COZeNQPi3nx3RNxPFBKyo1DyT_czP2zH2GhCK3JYnGe7V9GpEoSIOLsAQxaoZftiyqMszDe9pTDmlqysvYlsEALeS1-75m54cWoC6o5fUTFriyTppGDTDy7vZ3SEVEjBtVNSSHLEBONer3zpPRjrRSWo_7eurFS8aNygRsEM6wSnfMmIvuIoFtF7LVPXgVOkQc9QUQwBXhcMwA2jPJRmKeqSysdwL41rvm7jImAkPiaAZKaiEAwg82QX8i_PNYDUzfqj1HqBuJadQ
    depends_on:
      - db

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
